import './header.js';
import './footer.js';
import './swipers.js';
import './hover-circle.js';
import './single-product-desc.js';
import './ajax-checkout-and-cart.js';
import './cart-sidebar.js';
import './archive-products.js';
import './search-box.js';
import './ajax-search.js';
import './ajax-wishlist.js';
import './contact-form.js';
import './product-image-hover.js';
import './ajax-product-archive-load.js';
// import './ajax-discount-code.js';
// import './dynamic-shipping-pick-up.js';
// import './dynamic-payment-option.js';
import './newsletter-toggle.js';
// import './checkout-validation.js';
// import './ajax-shipping.js';
import './wishlistlist-active-heart.js';
import './move-omnisend-checkbox.js';
import './single-product-duk.js';
